
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("morador/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("morador", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit morador</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="Nome">Nome</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Nome", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Cpf">Cpf</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Cpf", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Rg">Rg</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Rg", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="TelContato">TelContato</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("TelContato", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="DataNasc">DataNasc</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("DataNasc", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="Foto">Foto</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("Foto", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
